name: "Tests"

on:
  [ push, pull_request ]

jobs:

  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: docker-compose
        run: docker-compose -f ../.actions-docker-compose.yml up -d

      - name: pip install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r dev-requirements.txt

      - run: pytest --disable-pytest-warnings --cov=./
      - run: behave --format progress2 --logging-level=ERROR
      - run: flake8
      - run: mypy .

      - name: init
        run: python manage.py initialize_data

  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: npm install
      - run: npm run build
